/*
 * @Author: your name
 * @Date: 2022-02-20 11:23:16
 * @LastEditTime: 2022-02-20 17:07:00
 * @LastEditors: Please set LastEditors
 * @Description: 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 * @FilePath: \changshengdev\template\vue_cli\home\bootstrap\tpl\src\vue.config.js
 */
module.exports = {
    chainWebpack: (config) => {
        config.devServer.disableHostCheck(true).port(7961).end();
    }
};